config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "items#index"
  resources :items
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?


  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"] 
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :sports, :skill, :achievement])
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index 
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to root_path
    else
      render :new
    end
  end


  private

  def item_params
    params.require(:item).permit(:image, :title,:subtitle,:price,:date).merge(user_id: current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/index.html.erb
<%= render "shared/header" %>

  <%= link_to image_tag("CanDo TOP.png", class:"main-top"), "#" %>
    <div class="what_cando">
      <h2>CanDoとは？</h2>
      <div class="what_main">
        <div class="what_left">
          <h3>あなたの 'I <span class="strong">CanDo</span> it!'を<br>
          <span class="strong">'Want'</span>する人のもとへ</h3>
          <p class="what_cando_text">スポーツのスキルを商品に<br>
          スポーツ選手のマッチングサービスアプリ</p>

          <p class="what_cando_text">コーチや、練習相手、試合要員など<br>
          使い方は様々!
          </p>
        </div>
        <div class="what_right">
        <%= image_tag "/assets/coaching.jpeg", class:"coach" %>
        </div>
      </div>
      <%= link_to 'あなたのCanDoを登録する', new_item_path, class: "new_cando" %>
    </div>
    <div class="what-what">
      <h2>Wantとは？</h2>
      <ul class="what-lists">
        <li class="what-list">
          <%= image_tag "/assets/look-phone.png", class:"what-img" %>
          <h4>Candoを探す</h4>
        </li>
        <li class="what-list">
          <%= image_tag "/assets/look-phone.png", class:"what-img" %>
         <h4>Wantを見つける</h4>
        </li>
        <li class="what-list">
          <%= image_tag "/assets/look-phone.png", class:"what-img" %>
         <h4>希望条件を確認後、マッチング</h4>
        </li>
      </ul>
    </div>
    <div class="cando-index">
      <h2>CanDo一覧を見る</h2>
      <ul class='cando-lists'>
        <% @items.each do |item|%>
          <li class=cando-list>
            <%= image_tag item.image.variant(resize: '300x200'), class: 'cando-image' if item.image.attached? %>
            <%= item.title%>
            <%= item.subtitle%>
            <%= item.date%>
            <%= item.price%>円/1時間
          </li>
        <% end %>
      </ul>
    </div>



  </div>
<%= render "shared/footer" %> 

app/views/items/new.html.erb
<div class="items-sell-contents">
  <header class="items-sell-header">


  </header>
  <div class="items-sell-main">
    <h2 class="items-sell-title">CanDOの情報を入力</h2>
    <%= form_with model: @item, local: true do |f| %>

    <%= render 'shared/error_messages', model: f.object %>

    <%# 商品画像 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        写真
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"item-image" %>
      </div>
    </div>
    <%# /商品画像 %>
    <%# 商品名と商品説明 %>
    <div class="new-items">
      <div class="weight-bold-text">
        商品名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :title, class:"items-text", id:"item-name", placeholder:"タイトル（必須 40文字まで)", maxlength:"40" %>
      <div class="items-explain">
        <div class="weight-bold-text">
          内容
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :subtitle, class:"items-text", id:"item-info", placeholder:"商品の説明（必須 1,000文字まで）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。" ,rows:"7" ,maxlength:"1000" %>
      </div>
    </div>
          <label class="form-text">希望日時</label>
      <span class="indispensable">必須</span>
    </div>
    <div class='input-birth-wrap'>
      <%= raw sprintf(
                  f.date_select(
                    :date,
                    class:'select-birth',
                    id:"birth-date",
                    use_month_numbers: true,
                    prompt:'--',
                    start_year: 2022,
                    end_year: (Time.now.year + 1),
                    date_separator: '%s'),
                  "<p> 年 </p>", "<p> 月 </p>") + "<p> 日 </p>" %>
    </div>
    <%# /商品名と商品説明 %>
    <%# 販売価格 %>
    <div class="sell-price">
      <div class="weight-bold-text question-text">
        <span>販売価格</span>
        <a class="question" href="#">?</a>
      </div>
      <div>
        <div class="price-content">
          <div class="price-text">
            <span>価格</span>
            <span class="indispensable">必須</span>
          </div>
          <span class="sell-yen">¥</span>
          <%= f.text_field :price, class:"price-input", id:"item-price", placeholder:"例）300" %>
        </div>
        <div class="price-content">
          <span>販売手数料 (10%)</span>
          <span>
            <span id='add-tax-price'></span>円
          </span>
        </div>
        <div class="price-content">
          <span>販売利益</span>
          <span>
            <span id='profit'></span>円
          </span>
        </div>
      </div>
    </div>
    <%# /販売価格 %>


    <div class="sell-btn-contents">
      <%= f.submit "出品する" ,class:"sell-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
    <%# /下部ボタン %>
  </div>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cando</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <p class="copyright">© CanDo</p>
</div>

app/views/shared/_header.html.erb
<%# CSS・・・assets/stylesheets/shared/header.css %>
<header class='top-page-header'>
    <div class="container">
      <h1 class="header-title">CanDo</h1>
      <div class='nav'>
        <ul class='lists-right'>
          <% if user_signed_in? %>
            <li><%= link_to current_user.nickname, "#", class: "user-nickname" %></li>
            <li><%= link_to 'ログアウト', destroy_user_session_path	, method: :delete, class: "logout" %></li>
          <% else %>
            <li><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
            <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
          <% end %>
        </ul>
      </div>
    </div>
</header>